<a href="https://colab.research.google.com/github/Saugat-Chaudhary/course22p2/blob/master/my_activities/pytorch_official_tutorials/60_minute_blitz/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [2]:
import torch
import numpy as np

## Tensors and their rankings

### Rank 0 tensor: Scalar
Scalar are just a number and are represented as rank 0 tensors.

In [3]:
# rank 0 tensors: Scalar
# just a single number
scalar = torch.tensor(2)
print(f'Rank 0 (Scalar) ndim: {scalar.ndim}')
print(f'tensor: {scalar}')

Rank 0 (Scalar) ndim: 0
tensor: 2


### Rank 1 tensor: Vector
Vector are just 1D array of numbers.

In [4]:
# rank 1 tensor: Vector (1D array)
vector = torch.tensor([1,2])
print(f'Rank 1 (Vector) ndim: {vector.ndim}')
print(f'tensor: {vector}')

Rank 1 (Vector) ndim: 1
tensor: tensor([1, 2])


### Rank 2 tensor: Matrix
A 2D grid (Rows, Columns)

In [5]:
# rank 2 tensor: Matrix (2D array)
matrix = torch.tensor([[0,0],[0,1]])
print(f'Rank 2 (Matrix) ndim: {matrix.ndim}')
print(f'tensor: {matrix}')

Rank 2 (Matrix) ndim: 2
tensor: tensor([[0, 0],
        [0, 1]])


## Rank 3 tensor: 3D Tensor
Often used for a single RGB image (Channels, Height, Width)

In [6]:
# rank 3 tensor: 3D Tensor
tensor_3d = torch.zeros((3, 224, 224)) #(Channels, Height, Width)

# This prints the DATA (the zeros)
print(f'tensor: {tensor_3d}')

# This prints the RANK (should be 3)
print(f'Rank (ndim): {tensor_3d.ndim}')

# This prints the SHAPE (should be torch.Size([3, 224, 224]))
print(f'Shape: {tensor_3d.shape}')

tensor: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
Rank (ndim): 3
Shape: torch.Size([3, 224, 224])


### Rank 4 tensor: 4D Tensor
Commonly used for a batch of images (Batch, Channels, Height, Width)

In [7]:
# rank 4 tensor: 4D Tensor
tensor_4d = torch.randn((32,3,224,224))
print(f'Rank 4 Tensor ndim: {tensor_4d.ndim}')
print(f'tensor: {tensor_4d}')

Rank 4 Tensor ndim: 4
tensor: tensor([[[[-6.8575e-01,  1.7463e+00,  4.8315e-01,  ..., -1.3227e+00,
           -1.5522e+00, -4.9044e-02],
          [-1.5783e+00,  1.8960e-01, -1.1075e+00,  ...,  1.1274e-01,
            5.4652e-01,  1.5721e+00],
          [-3.6643e-01, -5.4183e-01, -2.2460e+00,  ..., -6.3013e-01,
            1.0287e+00, -2.4764e-01],
          ...,
          [-5.1772e-01, -4.7448e-01, -1.2079e+00,  ...,  1.6679e+00,
            9.4502e-02, -3.8911e-01],
          [ 5.6047e-01, -4.1477e-01, -5.2370e-01,  ..., -1.7356e-01,
           -5.6026e-01,  1.3725e+00],
          [-2.7943e-01, -4.6740e-01,  1.0778e-01,  ..., -9.6011e-01,
            1.2392e+00, -1.7814e+00]],

         [[ 1.9288e+00,  4.7096e-01,  1.4692e+00,  ...,  2.1842e+00,
            1.0407e+00,  1.0697e-01],
          [ 1.1854e+00, -8.8884e-01,  8.6632e-01,  ...,  7.2076e-01,
            4.9218e-01,  5.6890e-01],
          [ 1.9830e-01, -1.9100e+00,  5.9914e-01,  ...,  2.1796e-01,
            9.3739e-01,  1.1

###_Note: why we used .zeros or .ones or .rands to create 3d or 4d tensor?_

| Function | What it does | Common Use Case |
|---------|--------------|-----------------|
| torch.zeros()| Fills with $0$ |Creating masks, padding, or empty image placeholders. |
| torch.ones() | Fills with $1$ | Initializing multipliers or "white" background masks. |
| torch.randn() | Fills with random numbers between -1 and 1 | Initializing model weights or simulating real-world data. |
| torch.rand() | Fills with random numbers between 0 and 1 | Initializing model weights or simulating real-world data. |

The simple answer is, we used .zeros(), .ones() or .randn() because it isn't possible for us to write a whole 3d or 4d tensor by typing as they are very big.

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [8]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.

- `x_ones`: We are saying we want tensors in the form of one but maintain the shape and datatype of x_data tensor.
- `x_rand`: We are saying we want random tensors with float as datatype but still maintain the shape of x_data tensor.

In [10]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6573, 0.9869],
        [0.7208, 0.8456]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.

- shape = (2,3,): we are saying, we need rank 2 tensor (matrix) with 2 rows and 3 columns. The trailing comma doesn't have any special meaning, it is same as saying (2,3).

_Note: Major catch, if we didn't specify the datatype for tensor then by default the pytorch will create tensor of float32 type as neural networks need precision._


In [11]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2172, 0.2222, 0.6054],
        [0.7857, 0.9525, 0.9756]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.

Tensors are usually stored in two types of devices:
1. CPU
2. GPU (cuda)
And if one tensor is in cpu and another is in gpu then any operation between those tensors will throw error so, it is important to check using method `tensor.device`.

In [12]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.

_Note: `dim=0` concatenates row wise and `dim=1` concatenates column wise._


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Multiplying tensors**
- **Element wise multiplication**

  ELement wise matrix multiplication requires both matrices to be of the same shape i.e. same number of rows and column.

  Operation: Each element in the result is A[i][j] * B[i][j].

  Matrix A:
  $[[1, 2, 3],
    [4, 5, 6]]$

  Matrix B:
  $[[ 7,  8,  9],
    [10, 11, 12]]$

  Hadamard Product:
  $[[ 7, 16, 27],
    [40, 55, 72]]$



In [16]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Matrix Multiplication:**

This computes the matrix multiplication between two tensors:

Matrix multiplication is an operation where two matrices are combined to form a new matrix. The general rule is that if you have matrix
A of size m × n and matrix B of size n × p, their product C=AB will be of size m×p. Each element $^cij$ in the result is calculated by taking the dot product of the i-th row of A and the j-th column of B.

Example: 2×3 and 3×2 Matrices

Let A =$ [[1, 0, 2, ],[−1, 3, 1]],

B = [[3, 1, 2, [1, 1, 0]]

The resulting matrix C will have size 2×2.

Step 1: Compute each element

$^c11$=1⋅3+0⋅2+2⋅1=3+0+2=5

$^c12$=1⋅1+0⋅1+2⋅0=1+0+0=1$

$^c21$=−1⋅3+3⋅2+1⋅1=−3+6+1=4

$^c22$=−1⋅1+3⋅1+1⋅0=−1+3+0=2

Step 2: Result

C=AB=$ [ [5, 1],[ 4 ,2] ]$

In [17]:
print(f"Tensor.T: {tensor.T}")
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In PyTorch, you can usually spot an in-place operation by the underscore (_) at the end of the function name.

- Standard Operation (Not in-place): y = x.add(5) — This leaves x alone and creates a brand new tensor y.

- In-Place Operation: x.add_(5) — This modifies the values inside x itself.


In [19]:
x = torch.tensor([1.0, 2.0])

# 1. Standard (Out-of-place)
y = x + 1  # Or x.add(1)
print(f"Standard - x: {x}, y: {y}")
# x is still [1, 2], y is [2, 3]

# 2. In-place
x.add_(1)
print(f"In-place - x: {x}")
# x has now changed to [2, 3]

print(tensor, "\n")
tensor.add_(5)
print(tensor)

Standard - x: tensor([1., 2.]), y: tensor([2., 3.])
In-place - x: tensor([2., 3.])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [21]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [22]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
